export const CREATE_POST = "POST/CREATE_POST";
export const CREATE_POST_ADD = "CREATE_POST_ADD";

export const FETCH_POST = "POST/FETCH_POST";
export const REQUEST_POSTS = "REQUEST_POSTS";

// export const REQUEST_CHANGED_POSTS = "REQUEST_CHANGED_POSTS";
// export const FETCH_CHANGED_POST = "FETCH_CHANGED_POST";

export const USER_POSTS = "USER_POSTS";
export const REQUEST_PAGE_POSTS = "REQUEST_PAGE_POSTS";
export const FETCH_ONE_POST = "FETCH_ONE_POST";

export const FETCH_LOGIN_USER = "FETCH_LOGIN_USER";
export const REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";

export const FETCH_AUTH_USER = "FETCH_AUTH_USER";
export const REQUEST_AUTH_USER = "REQUEST_AUTH_USER";

export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const FETCH_GET_COMMENTS = "FETCH_GET_COMMENTS";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_ADD = "CREATE_COMMENT_ADD";
